Vagrant.configure("2") do |config|
  
  config.vm.define "aderouinS" do |aderouinS|
    aderouinS.vm.box = "generic/alpine319"
    aderouinS.vm.box_version = "4.3.12"
    aderouinS.vm.network "private_network", ip: "192.168.56.110"
    aderouinS.vm.hostname = "aderouinS"
    aderouinS.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
      vb.name = "aderouinS"
    end
    aderouinS.vm.provision "shell", path: "provision-server.sh"
  end

  config.ssh.insert_key = false
  config.ssh.private_key_path = ["~/.vagrant.d/insecure_private_key", "~/.ssh/id_rsa"]
end

