global:
  edition: ce
  hosts:
    domain: local.gitlab
  ingress:
    configureCertmanager: false
    tls:
      enabled: false
  shell:
    authToken:
      token: "very-secret-token"

gitlab:
  webservice:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 512Mi

nginx-ingress:
  enabled: true

